-- ========================================================
-- NGO HELPER COMPLETE SUPABASE SCHEMA & SEED DATA SCRIPT
-- Paste and run this entire script in your Supabase SQL Editor
-- ========================================================

-- 1. CREATE TABLES (IF NOT EXISTS)
create table if not exists public.user_roles (
    id uuid primary key references auth.users(id) on delete cascade,
    role text not null check (role in ('volunteer', 'ngo')),
    created_at timestamptz default now()
);

create table if not exists public.volunteer_profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text not null,
    phone text,
    location text,
    bio text,
    skills text[],
    interests text[],
    availability text,
    created_at timestamptz default now()
);

create table if not exists public.ngo_profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    organization_name text not null,
    phone text,
    location text,
    description text,
    causes text[],
    organization_type text,
    website text,
    contact_person text,
    created_at timestamptz default now()
);

create table if not exists public.events (
    id bigint generated by default as identity primary key,
    ngo_id uuid not null references public.ngo_profiles(id) on delete cascade,
    title text not null,
    location text not null,
    date date not null,
    category text not null,
    spots integer not null check (spots > 0),
    description text,
    created_at timestamptz default now()
);

create table if not exists public.applications (
    id bigint generated by default as identity primary key,
    event_id bigint not null references public.events(id) on delete cascade,
    volunteer_id uuid not null references public.volunteer_profiles(id) on delete cascade,
    status text not null default 'applied'
        check (status in ('applied', 'accepted', 'rejected', 'completed', 'cancelled')),
    created_at timestamptz default now(),
    unique(event_id, volunteer_id)
);

-- 2. ENABLE ROW LEVEL SECURITY (RLS)
alter table public.user_roles enable row level security;
alter table public.volunteer_profiles enable row level security;
alter table public.ngo_profiles enable row level security;
alter table public.events enable row level security;
alter table public.applications enable row level security;

-- 3. RLS POLICIES
drop policy if exists "Users can insert their own role" on public.user_roles;
drop policy if exists "Users can view their own role" on public.user_roles;

create policy "Users can insert their own role"
on public.user_roles for insert to authenticated with check (auth.uid() = id);

create policy "Users can view their own role"
on public.user_roles for select to authenticated using (auth.uid() = id);

drop policy if exists "Volunteers can insert their own profile" on public.volunteer_profiles;
drop policy if exists "Volunteers can view profiles" on public.volunteer_profiles;
drop policy if exists "Volunteers can update their own profile" on public.volunteer_profiles;

create policy "Volunteers can insert their own profile"
on public.volunteer_profiles for insert to authenticated with check (auth.uid() = id);

create policy "Volunteers can view profiles"
on public.volunteer_profiles for select to authenticated using (true);

create policy "Volunteers can update their own profile"
on public.volunteer_profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "NGOs can insert their own profile" on public.ngo_profiles;
drop policy if exists "Anyone can view ngo profiles" on public.ngo_profiles;
drop policy if exists "NGOs can update their own profile" on public.ngo_profiles;

create policy "NGOs can insert their own profile"
on public.ngo_profiles for insert to authenticated with check (auth.uid() = id);

create policy "Anyone can view ngo profiles"
on public.ngo_profiles for select using (true);

create policy "NGOs can update their own profile"
on public.ngo_profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "Anyone can view events" on public.events;
drop policy if exists "NGOs can create events" on public.events;
drop policy if exists "NGOs can update their events" on public.events;
drop policy if exists "NGOs can delete their events" on public.events;

create policy "Anyone can view events"
on public.events for select using (true);

create policy "NGOs can create events"
on public.events for insert to authenticated
with check (
    auth.uid() = ngo_id
    and exists (
        select 1 from public.ngo_profiles where ngo_profiles.id = auth.uid()
    )
);

create policy "NGOs can update their events"
on public.events for update to authenticated
using (auth.uid() = ngo_id) with check (auth.uid() = ngo_id);

create policy "NGOs can delete their events"
on public.events for delete to authenticated using (auth.uid() = ngo_id);

drop policy if exists "Authenticated can view applications" on public.applications;
drop policy if exists "Volunteers can apply" on public.applications;
drop policy if exists "Volunteers can update own applications" on public.applications;
drop policy if exists "NGOs can update applications on their events" on public.applications;

create policy "Authenticated can view applications"
on public.applications for select to authenticated using (true);

create policy "Volunteers can apply"
on public.applications for insert to authenticated
with check (
    volunteer_id = auth.uid()
    and exists (
        select 1 from public.volunteer_profiles where volunteer_profiles.id = auth.uid()
    )
);

create policy "Volunteers can update own applications"
on public.applications for update to authenticated
using (volunteer_id = auth.uid()) with check (volunteer_id = auth.uid());

create policy "NGOs can update applications on their events"
on public.applications for update to authenticated
using (
    exists (
        select 1 from public.events
        where events.id = applications.event_id
        and events.ngo_id = auth.uid()
    )
)
with check (
    exists (
        select 1 from public.events
        where events.id = applications.event_id
        and events.ngo_id = auth.uid()
    )
);

-- 4. SEED SAMPLE EVENTS FOR ALL LOGGED-IN NGO USERS
DO $$
DECLARE
  ngo_rec RECORD;
BEGIN
  -- Loop over all NGO accounts created in ngo_profiles
  FOR ngo_rec IN SELECT id, organization_name FROM public.ngo_profiles LOOP
    INSERT INTO public.events (ngo_id, title, location, date, category, spots, description)
    VALUES
      (ngo_rec.id, 'Hussain Sagar Lake Cleanliness Drive', 'Hyderabad', CURRENT_DATE + INTERVAL '5 days', 'Environment', 25, 'Join us to clear plastic waste and restore green cover along the lake bund.'),
      (ngo_rec.id, 'Free Health & Eye Screening Camp', 'Bangalore', CURRENT_DATE + INTERVAL '10 days', 'Healthcare', 15, 'Assisting medical team with patient registration, eye test chart distribution, and queue management.'),
      (ngo_rec.id, 'Weekend Primary School Literacy Drive', 'Chennai', CURRENT_DATE + INTERVAL '7 days', 'Education', 12, 'Conducting interactive reading, storytelling, and basic computer workshops for kids.'),
      (ngo_rec.id, 'Stray Animal Care & Adoption Fair', 'Hyderabad', CURRENT_DATE + INTERVAL '14 days', 'Animals', 20, 'Helping manage adoption booths, grooming, and feeding rescued animals at the shelter.'),
      (ngo_rec.id, 'Community Meal Distribution Drive', 'Mumbai', CURRENT_DATE + INTERVAL '3 days', 'Food', 30, 'Packaging and distributing freshly cooked meals to daily wage worker communities.')
    ON CONFLICT DO NOTHING;
  END LOOP;
END $$;
